description: p
template:
  repo: web-template
  name: web
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: findInTree
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
